package org.openhab.binding.zwave.internal.protocol.security.crypto.interfaces;

import java.security.SecureRandom;

import org.openhab.binding.zwave.internal.protocol.security.crypto.ZWaveCryptoException;

public interface ZWaveCryptoAesCtrDrbg {
    static final byte[] PRNG_PERSONALIZATION_STRING = new byte[0];
    // per CC:009F.01.00.11.016
    static final byte[] NONCE_NONE = new byte[0];
    static final boolean USE_DERIVATION_FUNCTION = false;
    static final int OUTPUT_LENGTH = 16;

    /**
     * Initializes the PRNG per CC:009F.01.00.11.016 of the spec
     *
     * CC:009F.01.00.11.016 The PRNG MUST be implemented as an
     * AES-128 CTR_DRBG as specified in [26]. The following
     * profile MUST be used:
     * <ul>
     * <li>No derivation function</li>
     * <li>No reseeding counter</li>
     * <li>Personalization string of 0x00 repeated 32 times</li>
     * <li>Output length = 16 bytes</li>
     * <li>security_strength is not used</li>
     * </ul>
     * <p/>
     * CC:009F.01.00.11.018 The inner state of the PRNG MUST be
     * separated from the SPAN table.
     *
     * The entropy_input [26] for instantiating the PRNG MUST be
     * generated by a truly random source, e.g. white radio
     * noise. The PRNG MUST be hardware seeded.
     *
     */
    public SecureRandom buildAesCounterModeDeterministicRandomNumberGenerator(byte[] entrophyBytes,
            boolean makePredictionResistant) throws ZWaveCryptoException;

    public SecureRandom buildAesCounterModeDeterministicRandomNumberGenerator(SecureRandom entropyRandom,
            boolean makePredictionResistant) throws ZWaveCryptoException;
}
