package org.openhab.binding.zwave.internal.protocol.security.crypto;

import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.concurrent.TimeUnit;

import org.openhab.binding.zwave.internal.protocol.security.ZWaveSecurityNetworkKeys;
import org.openhab.binding.zwave.internal.protocol.security.crypto.interfaces.ZWaveCryptoAesAeadCcm;
import org.openhab.binding.zwave.internal.protocol.security.crypto.interfaces.ZWaveCryptoAesCtrDrbg;
import org.openhab.binding.zwave.internal.protocol.security.crypto.interfaces.ZWaveCryptoDiffieHellman;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.annotations.VisibleForTesting;

public class ZWaveCryptoOperationsFactory {
    private static final Logger logger = LoggerFactory.getLogger(ZWaveCryptoOperationsFactory.class);

    private static final int WAIT_FOR_STICK_ENTROPY_SECONDS = 10;

    private static final Object rngSetLockLock = new Object();
    private static final Object initLock = new Object();

    private static volatile ZWaveCryptoHardwareRngCoordinator hardwareRngCoordinator = null;
    @VisibleForTesting
    protected static ZWaveCryptoOperations instance = null;

    private static Exception initException = null;

    /**
     * Initializes system crypto per the zwave spec. May be slow depending on the system to gather entropy
     */
    public static void initFromConfig(ZWaveSecurityNetworkKeys networkSecurityKeysFromConfig) {
        logger.debug("initFromConfig starting");
        synchronized (initLock) {
            logger.debug("initFromConfig in2");
            if (instance != null) {
                throw new ZWaveCryptoRuntimeException(
                        "ZWaveCryptoOperationsFactory.initFromConfig should only be called once");
            } else {
                InitStopWatch stopWatch = new InitStopWatch();
                try {
                    final ZWaveCryptoAesAeadCcm aeadCcmProvider = new ZWaveCryptoAesAeadCcmBouncyCastle();
                    final ZWaveCryptoAesCtrDrbg ctrDrbgProvider = new ZWaveCryptoAesCtrDrbgBouncyCastleBuilder();
                    final ZWaveCryptoDiffieHellman diffieHellmanProvider = new ZWaveCryptoDiffieHellmanJdk();
                    stopWatch.reset();
                    SecureRandom entropyRandom = waitForHardwareBaseEntropy();
                    SecureRandom prng = initPrngAccordingToZwaveSpec(ctrDrbgProvider, entropyRandom);
                    logger.debug("crypto init timing: {}", stopWatch.stop("prng"));
                    instance = new ZWaveCryptoOperations(networkSecurityKeysFromConfig, aeadCcmProvider,
                            ctrDrbgProvider, diffieHellmanProvider, prng);
                    logger.debug("initFromConfig: notifyAll");
                    initLock.notifyAll();
                } catch (ZWaveCryptoException | RuntimeException e) {
                    initException = e;
                    throw new ZWaveCryptoRuntimeException("Error during crypto init", e);
                } finally {
                    logger.debug("initFromConfig ZWave crypto init timings: {}", stopWatch.toString());
                }
            }
        }
    }

    /**
     * CC:009F.01.00.11.017 The entropy_input [26] for instantiating the PRNG MUST be generated by a truly random
     * source, e.g. white radio noise. The PRNG MUST be hardware seeded.
     */
    private static SecureRandom waitForHardwareBaseEntropy() {
        InitStopWatch stopWatch = new InitStopWatch();
        synchronized (rngSetLockLock) {
            while (ZWaveCryptoOperationsFactory.hardwareRngCoordinator == null) {
                try {
                    rngSetLockLock.wait();
                    logger.debug("rngSetLockLock woke up {}", Thread.currentThread().getName());
                } catch (InterruptedException e) {
                    // TODO: DB handle exception
                }
            }
        }
        SecureRandom entropyGenerator;

        // TODO: make a subclass of SecureRandom that collects entrophy in the background from the stick. Also, find a
        // stick that supports it
        // if (hardwareRngCoordinator.isSupportsRandom()) {
        // try {
        // byte[] randomBytes = hardwareRngCoordinator.waitForRandom(TimeUnit.SECONDS,
        // WAIT_FOR_STICK_ENTROPY_SECONDS);
        // if (randomBytes == null) {
        // logger.debug(
        // "hardwareBaseEntropy: controller does not support GET_RANDOM, failing back to SecureRandom");
        // }
        // logger.debug("hardwareBaseEntropy: returning controller generated bytes");
        // return randomBytes;
        // } catch (ZWaveCryptoException e) {
        // // SPEC_VIOLATION Out of compliance with the zwave spec as it requires a hardware
        // // source of entropy. See CC:009F.01.00.11.017
        // logger.debug(
        // "hardwareBaseEntropy: error from controller during GET_RANDOM, failing back to SecureRandom",
        // e);
        // }
        // }

        // The stick doesn't support the GetRandom command or it failed; use SecureRandom instead
        stopWatch.reset();
        try {
            entropyGenerator = SecureRandom.getInstanceStrong();
            logger.debug("security init timing: {}", stopWatch.stop("SecureRandom.getInstanceStrong"));
        } catch (NoSuchAlgorithmException e) {
            logger.debug(
                    "waitForHardwareBaseEntropy: error during init of SecureRandom.getInstanceStrong(), failing back to new SecureRandom()",
                    e);
            stopWatch.reset();
            entropyGenerator = new SecureRandom();
            logger.debug("security init timing: {}", stopWatch.stop("SecureRandom()"));
        }

        logger.debug(
                "hardwareBaseEntropy: returning SecureRandom bytes " + stopWatch.stop("waitForHardwareBaseEntropy"));
        return entropyGenerator;
    }

    /**
     * Initializes the PRNG per CC:009F.01.00.11.016 of the spec
     *
     * CC:009F.01.00.11.016 The PRNG MUST be implemented as an AES-128 CTR_DRBG as specified in [26]. The following
     * profile MUST be used:
     * <ul>
     * <li>No derivation function</li>
     * <li>No reseeding counter</li>
     * <li>Personalization string of 0x00 repeated 32 times</li>
     * <li>Output length = 16 bytes</li>
     * <li>security_strength is not used</li>
     * </ul>
     * <p/>
     * CC:009F.01.00.11.018 The inner state of the PRNG MUST be separated from the SPAN table.
     *
     * The entropy_input [26] for instantiating the PRNG MUST be generated by a truly random source, e.g. white radio
     * noise. The PRNG MUST be hardware seeded.
     *
     * @param ctrDrbgProvider
     */
    private static final SecureRandom initPrngAccordingToZwaveSpec(ZWaveCryptoAesCtrDrbg ctrDrbgProvider,
            SecureRandom entropyRandom) throws ZWaveCryptoException {
        // TODO: DB we're going to need more entropy, right? Need to pass a securerandom here and override the
        // constructor...
        InitStopWatch stopWatch = new InitStopWatch();
        SecureRandom random = ctrDrbgProvider.buildAesCounterModeDeterministicRandomNumberGenerator(entropyRandom,
                true);
        stopWatch.stop("initPrngAccordingToZwaveSpec");
        // Use it to ensure it works correctly
        random.nextBytes(new byte[1]);
        return random;
    }

    /**
     * Returns the singleton instance - may block if initialization is still underway
     */
    public static ZWaveCryptoOperations getCryptoProvider() {
        synchronized (initLock) {
            if (initException != null) {
                logger.warn("Crypto initialization failed, S2 security will not work because of {}",
                        initException.getMessage());
                return null;
            }
            long startTime = System.currentTimeMillis();
            while (instance == null) { // per Java Concurrency in Practice by Brian Goetz
                try {
                    initLock.wait(15000);
                } catch (InterruptedException e) {
                    logger.debug("Caught InterruptedException while waiting for initLock, contining to wait: {}",
                            e.getMessage());
                }
                logger.debug("getCryptoProvider(); still waiting after {} seconds",
                        (TimeUnit.MILLISECONDS.toSeconds(System.currentTimeMillis() - startTime)),
                        new ZWaveCryptoException("getCryptoProvider(); still waiting after {} seconds"));
                // TODO: DB give up after a cert time?
            }
            return instance;
        }
    }

    public static void setHardwareRngCoordinator(ZWaveCryptoHardwareRngCoordinator hardwareRngCoordinator) {
        synchronized (rngSetLockLock) {
            ZWaveCryptoOperationsFactory.hardwareRngCoordinator = hardwareRngCoordinator;
            logger.debug("rngSetLockLock.notifyAll() {}", Thread.currentThread().getName());
            rngSetLockLock.notifyAll();
        }
    }

    public static boolean isInitialized() {
        synchronized (initLock) {
            return instance != null;
        }
    }

    private static class InitStopWatch {
        private long startTime = System.nanoTime();

        private String stop(String description) {
            long elaspedMs = TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - startTime);
            startTime = System.nanoTime();
            return description + "=" + elaspedMs + "ms";
        }

        public void reset() {
            startTime = System.nanoTime();
        }
    }
}
