package org.openhab.binding.zwave.internal.protocol.security.crypto;

import java.security.DrbgParameters.Capability;
import java.security.SecureRandom;

import org.openhab.binding.zwave.internal.protocol.security.crypto.interfaces.ZWaveCryptoAesCtrDrbg;

/**
 * TODO does Java 17 does not support AES CTR_DBRG?. Bouncy Castle has an implementation, but it is FIPS compliant which
 *
 *
 * @author Dave Badia
 *
 */
public class ZWaveCryptoAesCtrDrbgJdk implements ZWaveCryptoAesCtrDrbg {

    /**
     * Initializes the PRNG per CC:009F.01.00.11.016 of the spec
     *
     * CC:009F.01.00.11.016 The PRNG MUST be implemented as an
     * AES-128 CTR_DRBG as specified in [26]. The following
     * profile MUST be used:
     * <ul>
     * <li>No derivation function</li>
     * <li>No reseeding counter</li>
     * <li>Personalization string of 0x00 repeated 32 times</li>
     * <li>Output length = 16 bytes</li>
     * <li>security_strength is not used</li>
     * </ul>
     * <p/>
     * CC:009F.01.00.11.018 The inner state of the PRNG MUST be
     * separated from the SPAN table.
     *
     * The entropy_input [26] for instantiating the PRNG MUST be
     * generated by a truly random source, e.g. white radio
     * noise. The PRNG MUST be hardware seeded.
     * TODO: DB delete his javadoc
     */
    @Override
    public SecureRandom buildAesCounterModeDeterministicRandomNumberGenerator(byte[] entropyInputBytes,
            boolean makePredictionResistant) throws ZWaveCryptoException {
        final int strength = 128; // TODO:is this right? is it ignored?
        Capability capability = Capability.NONE;
        try {
            throw new UnsupportedOperationException(
                    "No way to specify AES w/o messing w JVM and This implementation reads fresh entropy from the system default entropy source determined by the security property securerandom.source. Entropy input is hardcoded to https://docs.oracle.com/javase%2F9%2Fdocs%2Fapi%2F%2F/java/security/DrbgParameters.html");
            // TODO: DB what if we need makePredictionResistant, only option is Capability.PR_AND_RESEED
            // return SecureRandom.getInstance("DRBG",
            // DrbgParameters.instantiation(strength, capability, PRNG_PERSONALIZATION_STRING));
        } catch (RuntimeException e) {
            throw new ZWaveCryptoRuntimeException("Error during init of SecureRandom DRBG", e);
        }
    }
}
